version: '3.8'

services:
  base-image:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.base
    image: chompchomp-base
  api:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27109
      - MONGO_DB=chompchomp
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
      - base-image

  scheduler:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.scheduler
    container_name: scheduler
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.worker
    container_name: worker
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27109
      - MONGO_DB=chompchomp
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
      - base-image

  slow:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile slow
    container_name: slow
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27109
      - MONGO_DB=chompchomp
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
      - base-image

  admin:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.flower
    container_name: admin
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:      
      - redis      

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: frontend
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src/
        - action: sync+restart
          path: ./frontend/nginx.conf
          target: /etc/nginx/nginx.conf
    ports:
      - "3001:80"
    depends_on:
      - api
      - admin

  redis:
    image: redis:6.2
    container_name: redis

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    command: mongod --port 27109 --bind_ip_all
    ports:
      - "27109:27109"
