FROM chompchomp-base

# Copy the rest of the application code into the container
COPY data.py .
COPY tasks.py .
COPY main.py .

RUN mkdir -p /root/.local/share/webtech

# Expose the port the app runs on
EXPOSE 8888

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8888"]