FROM chompchomp-base

# Copy the rest of the application code into the container
COPY main.py .

RUN mkdir -p /root/.local/share/webtech

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]